---
name: App-CPAN-Mini-Visit
version: 0.006
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: explore each distribution in a minicpan repository
license: apache
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
build_requires:
  File::Temp: 0.2
  IO::CaptureOutput: 1.0801
  IO::File: 0
  Test::More: 0.62
requires:
  Archive::Extract: 0.28
  CPAN::Mini: 0.572
  Exception::Class::TryCatch: 1.12
  File::Basename: 0
  File::Find: 0
  File::pushd: 1
  Getopt::Lucid: 0.16
  Path::Class: 0.16
  Pod::Usage: 1.35
  perl: 5.01
configure_requires:
  Module::Build: 0.35
provides:
  App::CPAN::Mini::Visit:
    file: lib/App/CPAN/Mini/Visit.pm
    version: 0.006
generated_by: Module::Build version 0.3502
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - examples
    - inc
    - t
